[phases.setup]
nixPkgs = ['jdk17']

[phases.install]
cmds = ['chmod +x gradlew']

[phases.build]
cmds = [
  'java -version',
  './gradlew clean bootJar --no-daemon --info'
]

[start]
cmd = 'java -Dserver.port=$PORT -jar build/libs/borealis-0.0.1-SNAPSHOT.jar'
