services:
  - type: web
    name: borealis
    env: docker
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -Dserver.port=$PORT -jar build/libs/borealis-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
