spring.application.name=borealis

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Content location
content.base-path=classpath:content/
content.blog-path=${content.base-path}blog/
content.projects-path=${content.base-path}projects/
content.notes-path=${content.base-path}notes/

# Server configuration
server.port=8080
server.compression.enabled=true
server.compression.mime-types=text/html,text/css,application/javascript

# Logging
logging.level.com.betuince.borealis=DEBUG
